version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: greenwez raw data source
    tables:
      - name: sales
        identifier: raw_gz_sales 
        tests:
          - unique:
              column_name: "(orders_id || '_' || pdt_id)"

        description: sales of greenwez
        columns:
          - name: date_date
            description:  date of purchase
          - name: orders_id
            description: orders identifier
          - name: pdt_id
            description: product identifier
          - name: revenue
            description: total income 
          - name: quantity
            description: number of sales per order
      - name: product
        identifier: raw_gz_product
        description: products of greenwez
        columns:
          - name: products_id
            description: products  identify
            tests:
              - unique
              - not_null
                
          - name: purchSE_PRICE
            description: product sale price
      - name: ship
        identifier: raw_gz_ship
        description: shipping details of greenwez
        columns:
          - name: orders_id
            description: orders identifier
            tests:
              - unique
               - not_null
          - name: shipping_fee_1
            description: shipping fee       
           
          - name: shipping_fee
            description: shipping fee
          - name: logCost
            description: cost of logistics
          - name: ship_cost
            description: cost of shipping

      - name: adwords
        identifier: raw_gz_adwords
 
        description: sales of adwords
        columns:
          - name: date_date
            description:  date of purchase
          - name: paid_source
            description: the source where data is coming from
          - name: campaign_key
            description: campaign identifier
          - name: camPGN_name
            description: name of the campaign
          - name: ads_cost
            description: cost of adverts
          - name: impression
            description: nb of impression
          - name: click
            description: nb of clicks          

      - name: bing
        identifier: raw_gz_bing
 
        description: sales of bing
        columns:
          - name: date_date
            description:  date of purchase
          - name: paid_source
            description: the source where data is coming from
          - name: campaign_key
            description: campaign identifier
          - name: camPGN_name
            description: name of the campaign
          - name: ads_cost
            description: cost of adverts
          - name: impression
            description: nb of impression
          - name: click
            description: nb of clicks          

      - name: criteo
        identifier: raw_gz_criteo
 
        description: sales of criteo
        columns:
          - name: date_date
            description:  date of purchase
          - name: paid_source
            description: the source where data is coming from
          - name: campaign_key
            description: campaign identifier
          - name: camPGN_name
            description: name of the campaign
          - name: ads_cost
            description: cost of adverts
          - name: impression
            description: nb of impression
          - name: click
            description: nb of clicks          

      - name: facebook
        identifier: raw_gz_facebook
 
        description: sales of facebook
        columns:
          - name: date_date
            description:  date of purchase
          - name: paid_source
            description: the source where data is coming from
          - name: campaign_key
            description: campaign identifier
          - name: camPGN_name
            description: name of the campaign
          - name: ads_cost
            description: cost of adverts
          - name: impression
            description: nb of impression
          - name: click
            description: nb of clicks          

